/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package webScrappingExample;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        WebScrapping classUnderTest = new WebScrapping();
       // assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
